insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (10, 'N', 'employee.view.home', 'Employee viewing homepage.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (11, 'Y', 'employee.view.creditxfer', 'Employee viewing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (12, 'N', 'employee.print.creditxfer', 'Employee printing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (13, 'Y', 'employee.save.creditxfer', 'Employee saving creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (20, 'N', 'reviewer.view.home', 'Reviewer viewing homepage.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (21, 'N', 'reviewer.view.creditxfer', 'Reviewer viewing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (22, 'N', 'reviewer.print.creditxfer', 'Reviewer printing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (23, 'N', 'reviewer.save.creditxfer', 'Reviewer saving creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (30, 'N', 'admin.view.home',      'Approver viewing homepage.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (31, 'N', 'admin.view.creditxfer',   'Approver viewing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (32, 'N', 'admin.print.creditxfer',  'Approver printing creditxfer feature.')
insert into UHAPP_DB.ACTION (ACTION_ID, ACTION_ENABLED, ACTION_CODE, ACTION_DESCRIPTION) values (33, 'N', 'admin.save.creditxfer',   'Approver saving creditxfer feature.')
insert into UHAPP_DB.UNIQUE_UH_NUMBER_V (UH_NUMBER) values (89999999)
insert into UHAPP_DB.UNIQUE_UH_NUMBER_V (UH_NUMBER) values (10000001)
insert into UHAPP_DB.UNIQUE_UH_NUMBER_V (UH_NUMBER) values (10000002)
insert into UHAPP_DB.UNIQUE_UH_NUMBER_V (UH_NUMBER) values (10000003)
insert into UHAPP_DB.UNIQUE_UH_NUMBER_V (UH_NUMBER) values (10000004)
insert into UHAPP_DB.PS_MESSAGE (MSG_ID, MSG_ENABLED, MSG_TYPE_ID, MSG_TEXT) values (1, 'Y', 1, 'University of Hawaii Information Technology Services resides in a state-of-the-art, six-story, 74,000-square-foot facility located on the Manoa campus.')
insert into UHAPP_DB.PS_MESSAGE (MSG_ID, MSG_ENABLED, MSG_TYPE_ID, MSG_TEXT) values (2, 'Y', 1, 'The access to this system is restricted.<br/>If you believe you should have access, <br/> please send an email to <a href="mailto:duckart@hawaii.edu">duckart@hawaii.edu</a>.')
insert into UHAPP_DB.PS_MESSAGE (MSG_ID, MSG_ENABLED, MSG_TYPE_ID, MSG_TEXT) values (3, 'N', 1, 'For Future Use.')
